export const feedbackAction = Object.freeze({
  FEEDBACK_OPEN_SNACKBAR: 'FEEDBACK_OPEN_SNACKBAR',
  FEEDBACK_CLOSE_SNACKBAR: 'FEEDBACK_CLOSE_SNACKBAR',
  FEEDBACK_SET_MESSAGE_SNACKBAR: 'FEEDBACK_SET_MESSAGE_SNACKBAR',
  FEEDBACK_SNACK_TYPE: 'FEEDBACK_SNACK_TYPE'
});