export const formAction = Object.freeze({
  FORM_SET_OPEN_MODAL: 'FORM_SET_OPEN_MODAL',
  FORM_SET_MODAL_DATA: 'FORM_SET_MODAL_DATA',
  FORM_RESET_MODAL_DATA: 'FORM_RESET_MODAL_DATA',
  FORM_SET_MODE: 'FORM_SET_MODE',
  FORM_SET_PLACES: 'FORM_SET_PLACES',
});